/*
 * Swagger Schmettr
 *
 * This is the schmettr server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.ComponentModel.DataAnnotations;
using Data.Models;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Web.Attributes;

namespace Web.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class CommentApiController : ControllerBase
    { 
        /// <summary>
        /// Add a new comment
        /// </summary>
        /// <param name="body">Comment object that needs to be added to the message</param>
        /// <param name="messageId">ID of message to return</param>
        /// <response code="405">Invalid input</response>
        [HttpPost]
        [Route("/schmettr/schmettr/1.0.0/message/addComment{messageId}")]
        [ValidateModelState]
        [SwaggerOperation("AddComment")]
        public virtual IActionResult AddComment([FromBody]Comment body, [FromRoute][Required]long? messageId)
        { 
            //TODO: Uncomment the next line to return response 405 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(405);

            throw new NotImplementedException();
        }
    }
}
